# Generated by Django 3.2.13 on 2022-05-09 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='username',
        ),
    ]
